name: Run tests

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: true
      NODE_CACHE_KEY:
        type: string
        required: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: [lint, test, build]

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Load dependencies from cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: node_modules
          key: ${{ inputs.NODE_CACHE_KEY }}

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '${{ inputs.NODE_VERSION }}'

      - name: Run ${{ matrix.test }} test
        run: npm run ${{ matrix.test }}
